Ext.Loader.setConfig({
    enabled: true
});
Ext.application({
    models: [
        'SetModel',
        'CategoryModel',
        'AttributeModel',
        'CattributeModel',
        'EventModel',
        'EventTypeModel',
        'ImageModel',
        'UserModel',
        'CollectionModel',
        'StorageDeviceModel',
        'EvernoteAccountModel',
        'QueueModel',
        'KeyModel',
        'FilterModel',
        'GeographyModel',
        'ObjectModel'
    ],
    stores: [
        'SetTreeStore',
        'CategoryTreeStore',
        'PropertiesStore',
        'EventTreeStore',
        'ImagesStore',
        'UserStore',
        'CollectionsTreeStore',
        'StorageDevicesStore',
        'EvernoteAccountsStore',
        'QueueStore',
        'KeyStore',
        'AttributesStore',
        'CategoriesStore',
        'CollectionsStore',
        'EventsStore',
        'EventTypesStore',
        'FilterTreeStore',
        'GeographyStore',
        'ObjectsTreeStore'
    ],
    views: [
        'MainViewport',
        'StorageSettingsPanel',
        'EvernoteSettingsPanel',
        'UserManagerPanel',
        'KeyManagerPanel',
        'ImagesGridView',
        'CtxMnuCollection',
        'CtxMnuCategory',
        'CtxMnuAttribute',
        'CtxMnuEventType',
        'CtxMnuEvent',
        'CtxMnuDevice',
        'CtxMnuEvernote',
        'CtxMnuUser',
        'CtxMnuKey',
        'FormCreateCategory',
        'FormCreateAttribute',
        'FormCreateCollection',
        'FormCreateDevice',
        'FormCreateEvernoteAccount',
        'FormCreateUser',
        'FormCreateEventType',
        'FormCreateEvent',
        'FormCreateKey',
        'ImagesPanel',
        'FilterContextMenu',
        'ObjectContextMenu',
        'FilterTreePanel',
        'ObjectsFormPanel',
        'ObjectsTreePanel',
        'SearchFilterPanel',
        'ImageTabPanel'
    ],
    autoCreateViewport: true,
    name: 'BIS',
    launch: function() {
        // Remove Loading Div
        Ext.get('loading').remove();
        Ext.get('loading-mask').fadeOut({remove:true});
    }
});
