/*
 * File: app/view/SearchFilterPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SearchFilterPanel', {
    extend: 'Ext.panel.Panel',

    height: 652,
    width: 1249,
    layout: {
        type: 'border'
    },
    title: 'Search Filter',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    flex: 1,
                    region: 'west',
                    id: 'objectsTreePanel',
                    width: 150,
                    store: 'ObjectsTreeStore',
                    viewConfig: {
                        id: 'objectsTreeView'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'text',
                            flex: 1,
                            text: 'Object'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 3,
                    region: 'center',
                    border: false,
                    id: 'borderEastPanel',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'form',
                            flex: 1,
                            region: 'north',
                            height: 150,
                            id: 'objectFormPanel'
                        },
                        {
                            xtype: 'treepanel',
                            flex: 3,
                            region: 'center',
                            id: 'filterTreePanel',
                            store: 'FilterTreeStore',
                            viewConfig: {
                                id: 'filterTreeView'
                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'node',
                                    flex: 1,
                                    text: 'Node Type'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'object',
                                    flex: 3,
                                    text: 'Object'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});