/*
 * File: app/model/ImageModel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BIS.model.ImageModel', {
    extend: 'Ext.data.Model',
    alias: 'model.imageModel',

    fields: [
        {
            name: 'imageId'
        },
        {
            name: 'fileName'
        },
        {
            name: 'timestampModified'
        },
        {
            name: 'barcode'
        },
        {
            name: 'width'
        },
        {
            name: 'height'
        },
        {
            name: 'family'
        },
        {
            name: 'genus'
        },
        {
            name: 'specificEpithet'
        },
        {
            name: 'flickrPlantId'
        },
        {
            name: 'flickrModified'
        },
        {
            name: 'flickrDetails'
        },
        {
            name: 'picassaPlantId'
        },
        {
            name: 'picassaModified'
        },
        {
            name: 'gTileProcessed'
        },
        {
            name: 'zoomEnabled'
        },
        {
            name: 'processed'
        },
        {
            name: 'boxFlag'
        },
        {
            name: 'ocrFlag'
        },
        {
            name: 'namefinderFlag'
        },
        {
            name: 'namefinderValue'
        },
        {
            name: 'scientificName'
        },
        {
            name: 'collectionCode'
        },
        {
            name: 'globalUniqueIdentifier'
        },
        {
            name: 'path'
        },
        {
            name: 'ext'
        },
        {
            name: 'enFlag'
        }
    ]
});
