/*
 * File: app/model/ImageModel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BIS.model.ImageModel', {
    extend: 'Ext.data.Model',
    alias: 'model.imageModel',

    fields: [
        {
            name: 'image_id'
        },
        {
            name: 'filename'
        },
        {
            name: 'timestamp_modified'
        },
        {
            name: 'barcode'
        },
        {
            name: 'width'
        },
        {
            name: 'height'
        },
        {
            name: 'Family'
        },
        {
            name: 'Genus'
        },
        {
            name: 'SpecificEpithet'
        },
        {
            name: 'flickr_PlantID'
        },
        {
            name: 'flickr_modified'
        },
        {
            name: 'flickr_details'
        },
        {
            name: 'picassa_PlantID'
        },
        {
            name: 'picassa_modified'
        },
        {
            name: 'gTileProcessed'
        },
        {
            name: 'zoomEnabled'
        },
        {
            name: 'processed'
        },
        {
            name: 'box_flag'
        },
        {
            name: 'ocr_flag'
        },
        {
            name: 'namefinder_flag'
        },
        {
            name: 'namefinder_value'
        },
        {
            name: 'ScientificName'
        },
        {
            name: 'CollectionCode'
        },
        {
            name: 'GlobalUniqueIdentifier'
        },
        {
            name: 'path'
        },
        {
            name: 'ext'
        }
    ]
});