/*
 * File: app/store/ObjectsTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BIS.store.ObjectsTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'BIS.model.ObjectModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'objectsTreeStore',
            model: 'BIS.model.ObjectModel',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    root: 'records',
                    totalProperty: 'totalCount'
                }
            }
        }, cfg)]);
    }
});